### PR TITLE
Plugin rewrite and refactoring + new features

### PR DESCRIPTION
**Pull request by enscope**
- converted to prototype-based object code
- added option to specify custom pop-up html and selectors
- added option to allow pop-up to be always displayed
- included changes from master repository
- fully compatible with supplied examples

### CODE REVIEW

**Comment by etienne-martin** [comment]
Thanks for your work @enscope.

**Comment by etienne-martin** [comment]
Quick question, what is the "iOS support bug related to fast-click"?

**Comment by etienne-martin** [comment]
One more thing, can you update the example to demonstrate the "customPopOver" feature?

**Comment by enscope** [comment]
iOS support bug related to fast-click was an issue, that needed to be fixed, when that part, you (I hope understood correctly) called fast-click (the part, where touchend is propagated after highlighting) was not working correctly due to a mistake in the code (which caused in short, that only last area was highlightable on iOS devices).

As for the customPopOver, I will add some examples soon.
Thank you for including the code.

**Pull request merged**
